# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    steps:
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests
# jobs:
#   build-and-test:
#     macos:
#       xcode: 11.3.0
#     environment:
#       FL_OUTPUT_DIR: output
#       FASTLANE_LANE: test
#     steps:
#       - checkout
#       - run: bundle install
#       - run:
#           name: Fastlane
#           command: bundle exec fastlane $FASTLANE_LANE
#       - store_artifacts:
#           path: output
#       - store_test_results:
#           path: output/scan

#   beta:
#     macos:
#       xcode: 11.3.0
#     environment:
#       FL_OUTPUT_DIR: output
#       FASTLANE_LANE: beta
#     steps:
#       - checkout
#       - run: bundle install
#       - run:
#           name: Fastlane
#           command: bundle exec fastlane $FASTLANE_LANE
#       - store_artifacts:
#           path: output

# workflows:
#   build-test-beta:
#     jobs:
#       - build-and-test
#       - beta:
#           filters:
#             branches:
#               only: development
#           requires:
#             - build-and-test
